server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:${DATABASE_URL}}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

cors:
  allowed-origins: ${FRONTEND_URL:https://your-frontend.onrender.com}
