version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: task-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task-manager-network

  # Spring Boot Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: task-manager-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_manager_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - task-manager-network

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: task-manager-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - task-manager-network

volumes:
  mysql_data:

networks:
  task-manager-network:
    driver: bridge
